# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

# Define an environment variable
env:
  - SYMFONY_VERSION="3.0.*" DB=mysql

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - php bin/console d:m:d--env=test
  - php bin/console d:m:m --env=test
  - php bin/console d:f:l --env=test

# After a build, send email notification with the build results
notifications:
  email: lambot.rom@gmail.com