services:
    accommodation.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { city: 'partial', country: 'partial', region: 'partial' } ]
        tags: [ 'api_platform.filter' ]